site_name: alxxcold
site_description: Немного о себе..)
site_author: Григорьев Алексей Павлович

theme: 
  name: material 
  features: 
    - navigation.tabs 
    - navigation.sections 
    - navigation.top 
    - search.highlight 
    - search.share
  palette:
    - scheme: default
      primary: lime 
      accent: lime   
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: lime
      accent: lime 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Главная: index.md
  - О себе: about.md
  - Проекты: projects.md
  - Контакты: contacts.md

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alxxcold
    - icon: fontawesome/brands/telegram
      link: https://t.me/alxxcold